### ISSUE TITLE
clicker not working for me

### ISSUE THREAD

**Issue by jepistons** [KillerInk/TT2Clicker#1]
updated with all the settings that you suggested  start the bot then I started TT2  only see text view  but nothing happens, root is enable etc  btw I love the lay out

**Comment by KillerInk** [comment]
Oh sorry i forgot to tell, after you clicked on start bot and the textview appears and you started tt2, press vol- to start/stop it

**Comment by jepistons** [comment]
kool thanks please all that to the read me :)  keep up the work great work
