### ISSUE TITLE
Preview 2 issue

### ISSUE THREAD

**Issue by Danielvandervelden** [KillerInk/TT2Clicker#4]
Current MEMU version: 5.6
Android version 5.1
Cores using: Max performance 
Using hacked Hokage TT2 unlimited mana APK
480x800 screen size

Steps:
1. Downloaded the APK
2. Enabled the features and configured the bot
3. Clicked start bot (the small black box saying 'press vol- to start' appeared)
4. Switch back to TT2
5. Press vol-
6. Clickerbot has suddenly stopped working
7. I switch back to the Clickerbot application 
8. Suddenly it's running again (without clicking start)
9. Switch back to TT2 and press vol-
10. The timer starts counting down, but the bot doesn't actually do anything

Is there any other information I can give you?

**Comment by KillerInk** [comment]
Looks like you are not rooted. You have to root your memu seperate, its not enough to enable it in memu settings. Kingroot does work for me.
Root is needed to chmod input/event6 to fake touches

**Comment by KillerInk** [comment]
I will add a logger for easier trace down the problem

**Comment by Danielvandervelden** [comment]
Oh I didn't know the rooting in the memu menu wasn't enough! I'll use Kingroot when I get home. I didn't read anywhere here that it's needed so that's why. 

Thanks I'll report back tonight when I get back from work.

**Comment by KillerInk** [comment]
yeah confused me also. enable root in memu settings only allow to root memu.
i expected you know that :D
how to root:
 - turn off root in memu.
 - install and start kingroot (will fail to root)
 - turn on root in memu and restart
 - start again kingroot. (should now successfull root).

**Comment by Danielvandervelden** [comment]
All right so I took the following steps:

Completely fresh MEMU emulator
1. First installed Kingroot (which failed)
2. Enabled root and restarted
3. Started kingroot again and rooted succesfully
4. Installed the bot
5. Installed the Tap Titans 2 APK
6. Configured the bot
7. Started the bot and switched to TT2
8. Pressed vol- 

Again I got the error that the bot stopped unexpectedly. As soon as you manage to implement the log let me know! 

EDIT: I'm actually gonna try with the official TT2 app

UPDATE:

Okay so I got it 'working' in the form that it does not crash anymore. Yet again got a clean MEMU installation and now it doesn't crash. I can press vol- and the timer starts running, unfortunately nothing happens.

Are there any settings that I have to make sure to enable in order for it to work?

@KillerInk

**Comment by KillerInk** [comment]
Did you get asked about screenrecording permission after you started the clickerbot?
 Also memu must run in opengl. Screen recording crash with direct 3d.
Its confusing that its not working for you.
I can add the logger earliest tomorrow.

**Comment by Danielvandervelden** [comment]
Yea it's superweird that it's not working. When I start it up the first time I get a notification that it needs screenrecording permissions so I say yes start it up. Then when I click start bot it asks me if I want to give it root access and I click yes.

The menu config says OpenGL like it should. I'll see if I can record my steps and upload a video. Maybe there's something wrong with how I set it up.

**Comment by KillerInk** [comment]
pls check preview3. it has now a dev section where you can change the input.
it list all availible touch/keyboard devices.
For me its called "User Input" and is linked to /dev/input/event6.

**Comment by Danielvandervelden** [comment]
Here's a video of all my settings and what I'm doing:

https://www.youtube.com/watch?v=RcUKS9BlcZg 

It's Memu 5.6.2 and android version 5.1, OpenGL, Top settings, 60FPS, root enabled both by Kingroot and Memu.

@KillerInk does this help?

**Comment by KillerInk** [comment]
i think it has something todo with root.
pls check in kingroot that clickerbot is allowed.
in that window with root sucessfully is on bottom  "Monitor Root Authorization"

**Comment by Danielvandervelden** [comment]
Yea it says there Clickerbot and its option is set to allowed

**Comment by jepistons** [comment]
ya I have the same problem as you not sure whats going on

**Comment by KillerInk** [comment]
pls check the dev tab in the bot. it should look like this
![screenshot_2019-02-01-12-54-33](https://user-images.githubusercontent.com/30864229/52103438-edde0600-25e5-11e9-891f-e4202acbc098.png)
if nothing shows up something went wrong while rooting.
if user input is not event6, change it to the matching one

**Comment by jepistons** [comment]
Humm maybe I'll give you team viewer access  to see what's I am doing now

**Comment by Danielvandervelden** [comment]
For me it says (in the top bar) /dev/input/event6

Then right below it it says 'add device 1: /dev/input/event7

Then with me the device 2 is /dev/input/event6

Device 3 event 1
Device 4 event 0
device 5 event 3
device 6 event 2
device 7 event 5
device 8 event 4.

Maybe teamviewer would help indeed to see what we are doing wrong.. Where can I edit the user input because I can't seem to edit the contents only the title

**Comment by KillerInk** [comment]
Good news, its not a root issue. 
Yes you can change only the top item. The bottem content list only all availible input device.
One of them is called "User Input", this event must get applied to the top value.
If you dont have a User Input you can try and error event0-7.
With one of them it should start tapping.

**Comment by Danielvandervelden** [comment]
Hey there we go then! Now it's working indeed :). Gotta make sure to let people know hahaha

**Comment by KillerInk** [comment]
Should work too on latest memu with the correct event id
