### ISSUE TITLE
Auto prestige

### ISSUE THREAD

**Issue by Zrasas** [KillerInk/TT2Clicker#5]
Doesn't work atm even though there is an option, correct?

**Comment by KillerInk** [comment]
Prestige after time does not work.
But prestige after some boss fails seems more effective and work

**Comment by Zrasas** [comment]
Ok, thanks for the confirmation.
Prestige to boss fails is a no-go for farming, but might actually be good for afk pushing
during turneys.

**Comment by KillerInk** [comment]
problem is fixed now and add a random prestige time +10min.
