### ISSUE TITLE
Heroes automatically leveled after 10k

### ISSUE THREAD

**Issue by Danielvandervelden** [KillerInk/TT2Clicker#6]
Yo Killer, now it's working at last! So happy. Time for the feature requests hahaha

Could you implement an option in the 'Hero' tab where we could set a Boolean whether we already unlock all heroes or not? Basically this means that the bot never has to scroll down to unlock the first 20 heroes or so (since it always does that now when it starts the bot).

Thanks for all the hard work!

**Comment by KillerInk** [comment]
Its in work. My plan is to add how often level all heros should trigger. With set to 0 it will never trigger. But thats something for tomorrow. Tt2 Update drops in 47min
