### ISSUE TITLE
A discord channel

### ISSUE THREAD

**Issue by Danielvandervelden** [KillerInk/TT2Clicker#7]
Yo Killer,

Would it be maybe easy to have a discord channel? We can talk about some stuff there more easily should the need arise. I can manage it if you don't want the additional pain of doing so.

Let me know!

**Comment by KillerInk** [comment]
dont know if its needed. i have somewhere discord, but not realy using it.
feel free to open it.

**Comment by KillerInk** [comment]
[here we go ](https://discord.gg/6j8GSFg)
